apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-deploy
  labels:
    app: swiggy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: swiggy
          image: thoufeek/clone:latest   # Jenkins will update this with build number
          ports:
            - containerPort: 3000
          imagePullPolicy: Always   # ensures EKS always pulls the latest pushed image
---
apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
spec:
  type: LoadBalancer
  selector:
    app: swiggy
  ports:
    - port: 80        # external port (ELB)
      targetPort: 3000 # container port in your Node.js app
